spring:
  application:
    name: secret-archive
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
server:
  port: 9898
  servlet:
    context-path: /secret-archive