spring:
  application:
    name: secret-archive
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost/~/test
      username: sa
      password:
  sql:
    init:
      mode: always
server:
  port: 9898
  servlet:
    context-path: /secret-archive